language: r

sudo: required

compiler:
  - g++
    
r_packages:
  - devtools
  - Rcpp
  - Rcpp11

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - g++ -v

env:
  global:
    - CRAN: http://cran.rstudio.com

notifications:
  email:
  on_success: change
  on_failure: change
