# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('rcpp11test_rcpp_hello_world', PACKAGE = 'rcpp11test')
}

useCpp11 <- function() {
    .Call('rcpp11test_useCpp11', PACKAGE = 'rcpp11test')
}

